CREATE OR REPLACE FUNCTION update_RECONHECIMENTODECURSO()
RETURNS trigger AS $$ 
BEGIN
      UPDATE ReconhecimentoDeCurso SET codigoR = NEW.codigoR WHERE codigo = OLD.codigo
      IF NOT FOUND THEN RETURN NULL;
END;
$C$ LANGUAGE plpgsql;


CREATE TRIGGER update_recRC
BEFORE UPDATE
ON ReconhecimentoDeCurso
FOR EACH ROW
EXECUTE PROCEDURE update_RECONHECIMENTODECURSO();
